version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: heritagemk-postgres
    environment:
      POSTGRES_USER: eambari
      POSTGRES_PASSWORD: endrit123
      POSTGRES_DB: heritagemk
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: heritagemk-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/heritagemk
      SPRING_DATASOURCE_USERNAME: eambari
      SPRING_DATASOURCE_PASSWORD: endrit123
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: heritagemk-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend