apiVersion: apps/v1
kind: Deployment
metadata:
  name: heritagemk-backend
  namespace: heritagemk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heritagemk-backend
  template:
    metadata:
      labels:
        app: heritagemk-backend
    spec:
      containers:
        - name: backend
          image: eambari/heritagemk-backend:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
